name: 🐛 Bug Report
description: Submit a bug report to help us improve
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label:
            I have read the [Contributing Guidelines on
            issues](https://github.com/software-engineering-excellence/handbook/blob/main/CONTRIBUTING.md).
          required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
      options:
        - label: I'd be willing to fix this bug myself.
